export const contractColumns = [
  { title: '合同编号', dataIndex: 'contractNo', key: 'contractNo', width: 140 },
  { title: '学员ID', dataIndex: 'studentId', key: 'studentId', width: 100 },
  { title: '学员姓名', dataIndex: 'studentName', key: 'studentName', width: 120 },
  { title: '班主任', dataIndex: 'leadMentorName', key: 'leadMentorName', width: 100 },
  { title: '合同类型', dataIndex: 'contractType', key: 'contractType', width: 90, align: 'center' as const },
  { title: '美元金额', dataIndex: 'amountUsd', key: 'amountUsd', width: 120, align: 'right' as const },
  { title: '英镑金额', dataIndex: 'amountGbp', key: 'amountGbp', width: 120, align: 'right' as const },
  { title: '总课时', dataIndex: 'totalHours', key: 'totalHours', width: 90, align: 'right' as const },
  { title: '已用课时', dataIndex: 'usedHours', key: 'usedHours', width: 90, align: 'right' as const },
  { title: '剩余课时', dataIndex: 'remainingHours', key: 'remainingHours', width: 90, align: 'right' as const },
  { title: '开始日期', dataIndex: 'startDate', key: 'startDate', width: 110 },
  { title: '结束日期', dataIndex: 'endDate', key: 'endDate', width: 110 },
  { title: '续签原因', dataIndex: 'renewalReason', key: 'renewalReason', width: 120 },
  { title: '合同状态', dataIndex: 'contractStatus', key: 'contractStatus', width: 100, align: 'center' as const },
  { title: '操作', dataIndex: 'action', key: 'action', width: 160, fixed: 'right' as const },
]
