export const contractColumnDefs = [
  { dataIndex: 'contractNo', key: 'contractNo', width: 140, ellipsis: true, fixed: 'left' as const },
  { dataIndex: 'studentId', key: 'studentId', width: 100 },
  { dataIndex: 'studentName', key: 'studentName', width: 120, ellipsis: true },
  { dataIndex: 'leadMentorName', key: 'leadMentorName', width: 100, ellipsis: true },
  { dataIndex: 'contractType', key: 'contractType', width: 90, align: 'center' as const },
  { dataIndex: 'amountUsd', key: 'amountUsd', width: 120, align: 'right' as const },
  { dataIndex: 'amountGbp', key: 'amountGbp', width: 120, align: 'right' as const },
  { dataIndex: 'totalHours', key: 'totalHours', width: 90, align: 'right' as const },
  { dataIndex: 'usedHours', key: 'usedHours', width: 90, align: 'right' as const },
  { dataIndex: 'remainingHours', key: 'remainingHours', width: 90, align: 'right' as const },
  { dataIndex: 'startDate', key: 'startDate', width: 110 },
  { dataIndex: 'endDate', key: 'endDate', width: 110 },
  { dataIndex: 'renewalReason', key: 'renewalReason', width: 120, ellipsis: true },
  { dataIndex: 'contractStatus', key: 'contractStatus', width: 100, align: 'center' as const },
  { dataIndex: 'action', key: 'action', width: 160, fixed: 'right' as const },
]
