create table if not exists osg_student_mock_request (
  request_id bigint not null auto_increment,
  user_id bigint not null,
  request_group varchar(16) not null,
  request_type varchar(32) not null,
  course_type varchar(32) null,
  company varchar(128) null,
  job_status varchar(32) null,
  request_status varchar(32) not null,
  request_content varchar(128) null,
  request_reason varchar(1000) null,
  mentor_count varchar(32) null,
  preferred_mentor varchar(64) null,
  excluded_mentor varchar(64) null,
  mentor_name varchar(64) null,
  mentor_meta varchar(128) null,
  hours_feedback varchar(32) null,
  feedback_summary varchar(255) null,
  feedback_hint varchar(255) null,
  remark varchar(500) null,
  submitted_at datetime not null default current_timestamp,
  completed_at datetime null,
  create_time datetime not null default current_timestamp,
  update_time datetime not null default current_timestamp on update current_timestamp,
  primary key (request_id),
  key idx_osg_student_mock_request_user_group (user_id, request_group, submitted_at)
) engine=InnoDB default charset=utf8mb4;
