SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS osg_student_position (
    student_position_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    student_id BIGINT NOT NULL COMMENT '提交学生ID',
    student_name VARCHAR(64) DEFAULT NULL COMMENT '提交学生姓名快照',
    position_category VARCHAR(32) NOT NULL COMMENT '岗位分类',
    industry VARCHAR(64) NOT NULL COMMENT '行业分类',
    company_name VARCHAR(128) NOT NULL COMMENT '公司名称',
    company_type VARCHAR(64) DEFAULT NULL COMMENT '公司类别',
    company_website VARCHAR(255) DEFAULT NULL COMMENT '公司官网',
    position_name VARCHAR(128) NOT NULL COMMENT '岗位名称',
    department VARCHAR(128) DEFAULT NULL COMMENT '部门',
    region VARCHAR(32) NOT NULL COMMENT '大区',
    city VARCHAR(64) NOT NULL COMMENT '城市',
    recruitment_cycle VARCHAR(128) NOT NULL COMMENT '招聘周期',
    project_year VARCHAR(32) NOT NULL COMMENT '项目时间',
    deadline DATETIME DEFAULT NULL COMMENT '截止日期',
    position_url VARCHAR(255) DEFAULT NULL COMMENT '岗位链接',
    status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '审核状态：pending/approved/rejected',
    has_coaching_request VARCHAR(8) NOT NULL DEFAULT 'no' COMMENT '是否有辅导申请 yes/no',
    reject_reason VARCHAR(128) DEFAULT NULL COMMENT '拒绝原因',
    reject_note VARCHAR(500) DEFAULT NULL COMMENT '拒绝补充说明',
    reviewer VARCHAR(64) DEFAULT NULL COMMENT '审核人',
    reviewed_at DATETIME DEFAULT NULL COMMENT '审核时间',
    public_position_id BIGINT DEFAULT NULL COMMENT '通过后生成的公共岗位ID',
    flow_status VARCHAR(64) DEFAULT NULL COMMENT '通过后流转状态',
    remark VARCHAR(500) DEFAULT NULL COMMENT '备注',
    create_by VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (student_position_id),
    KEY idx_osg_student_position_status (status),
    KEY idx_osg_student_position_student (student_id),
    KEY idx_osg_student_position_coaching (has_coaching_request),
    KEY idx_osg_student_position_reviewed_at (reviewed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='学生自添岗位审核表';
