export const studentColumns = [
  { title: 'ID', dataIndex: 'studentId', key: 'studentId', width: 80 },
  { title: '英文姓名', dataIndex: 'studentName', key: 'studentName', width: 120 },
  { title: '邮箱', dataIndex: 'email', key: 'email', width: 160 },
  { title: '班主任', dataIndex: 'leadMentorName', key: 'leadMentorName', width: 100 },
  { title: '学校', dataIndex: 'school', key: 'school', width: 120, ellipsis: true },
  { title: '主攻方向', dataIndex: 'majorDirection', key: 'majorDirection', width: 140, ellipsis: true },
  { title: '投递岗位', dataIndex: 'positions', key: 'positions', width: 160 },
  { title: '总课时', dataIndex: 'totalHours', key: 'totalHours', width: 80, align: 'center' as const },
  { title: '岗位辅导', dataIndex: 'jobCoachingCount', key: 'jobCoachingCount', width: 90, align: 'center' as const },
  { title: '基础课', dataIndex: 'basicCourseCount', key: 'basicCourseCount', width: 80, align: 'center' as const },
  { title: '模拟应聘', dataIndex: 'mockInterviewCount', key: 'mockInterviewCount', width: 90, align: 'center' as const },
  { title: '剩余课时', dataIndex: 'remainingHours', key: 'remainingHours', width: 90, align: 'center' as const },
  { title: '提醒', dataIndex: 'reminder', key: 'reminder', width: 100 },
  { title: '账号状态', dataIndex: 'accountStatus', key: 'accountStatus', width: 90 },
  { title: '操作', dataIndex: 'action', key: 'action', width: 200, fixed: 'right' as const },
]

export const blacklistColumns = [
  { title: 'ID', dataIndex: 'studentId', key: 'studentId', width: 80 },
  { title: '英文姓名', dataIndex: 'studentName', key: 'studentName', width: 120 },
  { title: '邮箱', dataIndex: 'email', key: 'email', width: 160 },
  { title: '班主任', dataIndex: 'leadMentorName', key: 'leadMentorName', width: 100 },
  { title: '学校', dataIndex: 'school', key: 'school', width: 120 },
  { title: '主攻方向', dataIndex: 'majorDirection', key: 'majorDirection', width: 90 },
  { title: '黑名单原因', dataIndex: 'blacklistReason', key: 'blacklistReason', width: 160 },
  { title: '加入时间', dataIndex: 'blacklistTime', key: 'blacklistTime', width: 120 },
  { title: '操作人', dataIndex: 'operator', key: 'operator', width: 90 },
  { title: '操作', dataIndex: 'action', key: 'action', width: 200, fixed: 'right' as const },
]
