export const studentColumnDefs = [
  { dataIndex: 'studentId', key: 'studentId', width: 80, fixed: 'left' as const },
  { dataIndex: 'studentName', key: 'studentName', width: 120 },
  { dataIndex: 'email', key: 'email', width: 160 },
  { dataIndex: 'leadMentorName', key: 'leadMentorName', width: 100 },
  { dataIndex: 'school', key: 'school', width: 120, ellipsis: true },
  { dataIndex: 'majorDirection', key: 'majorDirection', width: 140, ellipsis: true },
  { dataIndex: 'positions', key: 'positions', width: 160 },
  { dataIndex: 'totalHours', key: 'totalHours', width: 80, align: 'center' as const },
  { dataIndex: 'jobCoachingCount', key: 'jobCoachingCount', width: 90, align: 'center' as const },
  { dataIndex: 'basicCourseCount', key: 'basicCourseCount', width: 80, align: 'center' as const },
  { dataIndex: 'mockInterviewCount', key: 'mockInterviewCount', width: 90, align: 'center' as const },
  { dataIndex: 'remainingHours', key: 'remainingHours', width: 90, align: 'center' as const },
  { dataIndex: 'reminder', key: 'reminder', width: 100 },
  { dataIndex: 'accountStatus', key: 'accountStatus', width: 90 },
  { dataIndex: 'action', key: 'action', width: 200, fixed: 'right' as const },
]

export const blacklistColumnDefs = [
  { dataIndex: 'studentId', key: 'studentId', width: 80, fixed: 'left' as const },
  { dataIndex: 'studentName', key: 'studentName', width: 120 },
  { dataIndex: 'email', key: 'email', width: 160 },
  { dataIndex: 'leadMentorName', key: 'leadMentorName', width: 100 },
  { dataIndex: 'school', key: 'school', width: 120 },
  { dataIndex: 'majorDirection', key: 'majorDirection', width: 90 },
  { dataIndex: 'blacklistReason', key: 'blacklistReason', width: 160 },
  { dataIndex: 'blacklistTime', key: 'blacklistTime', width: 120 },
  { dataIndex: 'operator', key: 'operator', width: 90 },
  { dataIndex: 'action', key: 'action', width: 200, fixed: 'right' as const },
]
