CREATE TABLE IF NOT EXISTS osg_interview_question (
  question_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  question_code VARCHAR(32) NOT NULL COMMENT '真题编号',
  student_id VARCHAR(64) NOT NULL COMMENT '学员ID',
  student_name VARCHAR(64) NOT NULL COMMENT '学员姓名',
  company_name VARCHAR(128) NOT NULL COMMENT '公司名称',
  department_name VARCHAR(128) NOT NULL COMMENT '部门名称',
  office_location VARCHAR(128) NOT NULL COMMENT '办公地点',
  interview_round VARCHAR(32) NOT NULL COMMENT '轮次',
  interview_status VARCHAR(32) NOT NULL COMMENT '面试状态',
  interview_date DATETIME DEFAULT NULL COMMENT '面试日期',
  interviewer_name VARCHAR(128) DEFAULT NULL COMMENT '面试官',
  question_count INT NOT NULL DEFAULT 0 COMMENT '题目数',
  question_items_json TEXT DEFAULT NULL COMMENT '题目列表JSON',
  supplemental_note TEXT DEFAULT NULL COMMENT '补充说明',
  source_type VARCHAR(32) NOT NULL COMMENT '来源类型',
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
  review_status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '审核状态 pending/approved/rejected',
  eligible_student_count INT NOT NULL DEFAULT 0 COMMENT '开放学生数',
  share_preview VARCHAR(255) DEFAULT NULL COMMENT '开放范围预览',
  reviewed_by VARCHAR(64) DEFAULT NULL COMMENT '审核人',
  reviewed_at DATETIME DEFAULT NULL COMMENT '审核时间',
  review_comment VARCHAR(255) DEFAULT NULL COMMENT '审核备注',
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  remark VARCHAR(255) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (question_id),
  UNIQUE KEY uk_osg_interview_question_code (question_code),
  KEY idx_osg_interview_question_review_status (review_status),
  KEY idx_osg_interview_question_company (company_name),
  KEY idx_osg_interview_question_submitted_at (submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='面试真题审核表';
