CREATE TABLE IF NOT EXISTS osg_class_record (
    record_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '课时记录ID',
    class_id VARCHAR(64) DEFAULT NULL COMMENT '课程ID/展示ID',
    mentor_id BIGINT NOT NULL COMMENT '导师ID',
    mentor_name VARCHAR(64) NOT NULL COMMENT '导师姓名',
    student_id BIGINT NOT NULL COMMENT '学员ID',
    student_name VARCHAR(64) NOT NULL COMMENT '学员姓名',
    course_type VARCHAR(32) NOT NULL COMMENT '课程类型',
    course_source VARCHAR(32) NOT NULL COMMENT '课程来源',
    class_date DATETIME NOT NULL COMMENT '上课日期',
    duration_hours DECIMAL(5,1) NOT NULL DEFAULT 0 COMMENT '课时时长',
    weekly_hours DECIMAL(5,1) NOT NULL DEFAULT 0 COMMENT '导师本周累计课时',
    status VARCHAR(16) NOT NULL DEFAULT 'pending' COMMENT '审核状态',
    class_status VARCHAR(32) DEFAULT NULL COMMENT '课程状态',
    rate VARCHAR(32) DEFAULT NULL COMMENT '评分/费率展示',
    topics VARCHAR(512) DEFAULT NULL COMMENT '课程主题',
    comments VARCHAR(512) DEFAULT NULL COMMENT '课程备注',
    feedback_content VARCHAR(1024) DEFAULT NULL COMMENT '课程反馈',
    review_remark VARCHAR(512) DEFAULT NULL COMMENT '审核备注',
    reviewed_at DATETIME DEFAULT NULL COMMENT '审核时间',
    submitted_at DATETIME NOT NULL COMMENT '提交时间',
    create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) DEFAULT NULL COMMENT '备注',
    INDEX idx_class_record_status (status),
    INDEX idx_class_record_mentor (mentor_id, status),
    INDEX idx_class_record_student (student_id, status),
    INDEX idx_class_record_submitted (submitted_at)
) COMMENT='课时审核记录表';
