FROM nginx:1.27-alpine

COPY nginx.conf /opt/osg/default.conf.template
COPY docker-entrypoint.sh /opt/osg/docker-entrypoint.sh
COPY dist/ /usr/share/nginx/html/

RUN chmod +x /opt/osg/docker-entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/opt/osg/docker-entrypoint.sh"]
